name: CI (development)

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test -- --runInBand

      - name: Build (renderer + main)
        run: npm run build

      - name: Upload build logs (debug)
        if: false
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            npm-debug.log
            build.log
